# Generated by Django 5.2.17 on 2026-09-10 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('view', models.URLField(blank=True, default='')),
                ('source', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
    ]
