# Generated by Django 5.2.17 on 2026-09-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
