# Generated by Django 5.2.17 on 2026-09-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_project_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
